# This is a basic workflow to help you get started with Actions

# name: CI/CD with Postman

# on:
#   schedule:
#     # - cron: '0 0 */4 * *'  # Menjalankan setiap 4 jam sekali pada waktu UTC
#     # - cron: '30 5 * * 1,3'  # Menjalankan setiap Senin dan Rabu pukul 5:30 AM UTC
#     # - cron: '30 5 * * 2,4'  # Menjalankan setiap Selasa dan Kamis pukul 5:30 AM UTC
#     - cron: '*/5 * * * *'
  
#   push:
#     branches:
#       - main

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '16'

#       - name: Install Newman globally
#         run: npm install -g newman

#       - name: Run Postman tests with Newman
#         run: newman run Test.postman_collection.json --environment Development.postman_environment.json
#         id: newman_run

#       - name: Send email notification via SendGrid
#         run: |
#           curl -X POST https://api.sendgrid.com/v3/mail/send \
#             -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
#             -H "Content-Type: application/json" \
#             -d '{
#                   "personalizations": [
#                     {
#                       "to": [{"email": "maulidwifairuz@gmail.com"}],
#                       "subject": "Postman Test Results"
#                     }
#                   ],
#                   "from": {"email": "${{ secrets.SENDGRID_EMAIL }}"},
#                   "content": [
#                     {
#                       "type": "text/plain",
#                       "value": "The Postman tests have completed. Here are the results: ${{ steps.newman_run.outputs.summary }}"
#                     }
#                   ]
#                 }'

#       - name: List files for debugging
#         run: ls -R

name: CI/CD with Postman and SendGrid

on:
  schedule:
    - cron: '*/5 * * * *'  # Menjalankan setiap 5 menit sekali
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Newman globally
        run: npm install -g newman

      - name: Run Postman tests with Newman
        run: newman run Test.postman_collection.json --environment Development.postman_environment.json
        id: newman_run

      - name: Show Newman test results
        echo "Test results: '${{ steps.newman_run.outputs.summary }}'"

      - name: Send email notification via SendGrid
        run: |
          response=$(curl -X POST https://api.sendgrid.com/v3/mail/send \
            -H "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "personalizations": [
                    {
                      "to": [{"email": "maulidwifairuz@gmail.com"}],
                      "subject": "Postman Test Results"
                    }
                  ],
                  "from": {"email": "${{ secrets.SENDGRID_EMAIL }}"},
                  "content": [
                    {
                      "type": "text/plain",
                      "value": "The Postman tests have completed. Here are the results: ${{ steps.newman_run.outputs.summary }}"
                    }
                  ]
                }')
          echo "Response from SendGrid: $response"

